// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlyK2LARlb-Exn_f1HaHa3HAdPqD-dsrQ',
    appId: '1:229837916669:web:5f06190211042dbfd33194',
    messagingSenderId: '229837916669',
    projectId: 'biolab-b78e8',
    authDomain: 'biolab-b78e8.firebaseapp.com',
    storageBucket: 'biolab-b78e8.firebasestorage.app',
    measurementId: 'G-NRXSC6DQHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8auqvZE6QHGVVn8bg4MlA81owwoJtCn0',
    appId: '1:229837916669:android:9797872bc5437f5fd33194',
    messagingSenderId: '229837916669',
    projectId: 'biolab-b78e8',
    storageBucket: 'biolab-b78e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj34dM1cZNc5evTmKDkLVX3EhWDXK2Bq4',
    appId: '1:229837916669:ios:4fafda83cfb629a8d33194',
    messagingSenderId: '229837916669',
    projectId: 'biolab-b78e8',
    storageBucket: 'biolab-b78e8.firebasestorage.app',
    iosBundleId: 'com.example.biolab',
  );
}
